In [2]:
import numpy as np

## indexing and slicing

In [3]:
arr1d=np.random.randint(1,100,10)
arr1d

array([99, 99, 45, 69,  1, 16, 96, 20, 26,  7])

In [4]:
print(arr1d[0])
print(arr1d[1])
print(arr1d[-1])
print(arr1d[-2])

99
99
7
26


In [5]:
arr1d[1:5]

array([99, 45, 69,  1])

In [9]:
arr1d[-1:-3:-1]

array([ 7, 26])

In [11]:
arr1d[-3::1]


array([20, 26,  7])

In [13]:
arr1d[-1:-5:-1]

array([ 7, 26, 20, 96])

### indexing and slicing in 2d array

In [16]:
arr2d=np.random.randint(1,200,size=(5,4))
arr2d

array([[ 27,  51, 121, 194],
       [179,  98,  76, 197],
       [157,  67, 135, 160],
       [139, 195, 134, 188],
       [179, 102,  53,  90]])

In [18]:
arr2d[0]

array([ 27,  51, 121, 194])

In [20]:
arr2d[3][2]

134

In [21]:
arr2d[-4][-3]

98

# slicing in 2d array

In [22]:
arr2d

array([[ 27,  51, 121, 194],
       [179,  98,  76, 197],
       [157,  67, 135, 160],
       [139, 195, 134, 188],
       [179, 102,  53,  90]])

In [23]:
# arr2d[row_slicing , column_slicing]
# row-slicing:[start:ending:step]
# column-slicing:[start:ending:step]


In [24]:
arr2d[:,:]

array([[ 27,  51, 121, 194],
       [179,  98,  76, 197],
       [157,  67, 135, 160],
       [139, 195, 134, 188],
       [179, 102,  53,  90]])

In [25]:
arr2d[0:2,:]

array([[ 27,  51, 121, 194],
       [179,  98,  76, 197]])

In [27]:
arr2d[:,0:2]

array([[ 27,  51],
       [179,  98],
       [157,  67],
       [139, 195],
       [179, 102]])

In [28]:
arr2d[::2,:]

array([[ 27,  51, 121, 194],
       [157,  67, 135, 160],
       [179, 102,  53,  90]])

In [29]:
arr2d[::,::-1]

array([[194, 121,  51,  27],
       [197,  76,  98, 179],
       [160, 135,  67, 157],
       [188, 134, 195, 139],
       [ 90,  53, 102, 179]])

In [30]:
arr2d[-2::,:]

array([[139, 195, 134, 188],
       [179, 102,  53,  90]])

In [32]:
arr2d[-2::,2:]

array([[134, 188],
       [ 53,  90]])

In [33]:
arr2d

array([[ 27,  51, 121, 194],
       [179,  98,  76, 197],
       [157,  67, 135, 160],
       [139, 195, 134, 188],
       [179, 102,  53,  90]])

In [34]:
arr2d[1:3,1:3]

array([[ 98,  76],
       [ 67, 135]])

In [43]:
arr2d[0:5:4,0:4:3]

array([[ 27, 194],
       [179,  90]])

In [46]:
arr2d.shape

(5, 4)

In [55]:
def extract_corner(array):
    print(array)
    print()
    n_row,n_col=array.shape
    return array[::n_row-1,::n_col-1]
    

In [56]:
extract_corner(np.random.randint(1,100,size=(4,7)))

[[69 64 50 93 20 13 22]
 [81 35 98  6 78 29 51]
 [97 14 83 24 25 69 61]
 [21 56 85 23 84 46 80]]



array([[69, 22],
       [21, 80]])

In [57]:
arr2d

array([[ 27,  51, 121, 194],
       [179,  98,  76, 197],
       [157,  67, 135, 160],
       [139, 195, 134, 188],
       [179, 102,  53,  90]])

In [59]:
arr2d[::-1,::-1]

array([[ 90,  53, 102, 179],
       [188, 134, 195, 139],
       [160, 135,  67, 157],
       [197,  76,  98, 179],
       [194, 121,  51,  27]])

In [60]:
arr2d.ndim

2

In [61]:
arr2d

array([[ 27,  51, 121, 194],
       [179,  98,  76, 197],
       [157,  67, 135, 160],
       [139, 195, 134, 188],
       [179, 102,  53,  90]])

In [66]:
n_row,n_col=arr2d.shape

n_row

5