# 3d array

In [1]:
import numpy as np

In [3]:
# arr2d[2d_slicing: row_slicing:column_slicing]
# 2d_slicing: start :end :step

In [56]:
arr3d=np.random.randint(1,100,size=(3,4,5))
arr3d

array([[[ 6, 26,  2, 23, 23],
        [96,  1, 89, 68, 44],
        [32, 25, 60, 39, 63],
        [74, 47,  6,  7, 57]],

       [[32, 82, 79, 96, 95],
        [29, 62, 60, 82, 16],
        [26, 70, 61, 78, 36],
        [74, 46, 39, 61, 93]],

       [[32, 98, 20, 12, 94],
        [49, 96, 54, 57, 47],
        [ 4, 78, 60, 18,  9],
        [84, 59, 21, 80, 54]]])

In [60]:
arr3d[0][2][3]

39

In [68]:
arr3d[0:3:2,2:4,2:4]

array([[[60, 39],
        [ 6,  7]],

       [[60, 18],
        [21, 80]]])

In [12]:
lists=['name','age','salary','ram',20,3000,'shyam',22,44000,'hari',12,6000,'ramesh',34,40000]
lists

['name',
 'age',
 'salary',
 'ram',
 20,
 3000,
 'shyam',
 22,
 44000,
 'hari',
 12,
 6000,
 'ramesh',
 34,
 40000]

In [69]:
arr=np.array(lists)
arr
arr.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [15]:
arr.ndim

1

In [16]:
arr.size

15

In [17]:
arr.size/3

5.0

In [18]:
arr.reshape(5,3)

array([['name', 'age', 'salary'],
       ['ram', '20', '3000'],
       ['shyam', '22', '44000'],
       ['hari', '12', '6000'],
       ['ramesh', '34', '40000']], dtype='<U11')

In [20]:
import pandas as pd

In [22]:
df=pd.DataFrame(arr.reshape(5,3))
df

0    1       2
0    name  age  salary
1     ram   20    3000
2   shyam   22   44000
3    hari   12    6000
4  ramesh   34   40000

## flaten(),ravel()

In [23]:
np.random.randint(1,100,size=(3,4,5))

array([[[14, 63, 98, 90, 93],
        [33, 11, 98, 29, 49],
        [13, 74, 48, 36, 48],
        [37, 53, 30, 63, 80]],

       [[74, 99, 95, 63, 28],
        [ 5, 83, 90, 73, 27],
        [37, 59,  8, 14, 28],
        [52, 64,  7, 46, 13]],

       [[ 6, 20, 83, 60, 81],
        [ 4,  3, 91, 90, 37],
        [21, 89, 34, 22, 22],
        [ 2,  9, 80, 47,  1]]])

In [24]:
arr3d.ravel()

array([54, 23, 87, 37, 79, 40, 81, 61, 65, 75, 89, 15, 24, 73, 80, 97, 99,
       28, 93, 22, 12, 73, 81, 65, 98, 72, 20,  1, 44, 67, 95, 23, 40, 50,
       17, 68,  4,  3, 89, 31, 50, 10, 24,  2, 47, 50, 70, 57, 63, 28, 25,
       20, 58, 73,  8, 58, 57, 55, 96, 62])

In [25]:
arr3d.flatten()

array([54, 23, 87, 37, 79, 40, 81, 61, 65, 75, 89, 15, 24, 73, 80, 97, 99,
       28, 93, 22, 12, 73, 81, 65, 98, 72, 20,  1, 44, 67, 95, 23, 40, 50,
       17, 68,  4,  3, 89, 31, 50, 10, 24,  2, 47, 50, 70, 57, 63, 28, 25,
       20, 58, 73,  8, 58, 57, 55, 96, 62])

In [26]:
arr3d.flatten().shape

(60,)

# operatpr in array

In [27]:
arr=np.random.randint(1,100,10)
arr

array([ 7, 45, 79, 95, 68, 18, 69, 38, 72, 96])

In [28]:
arr+10

array([ 17,  55,  89, 105,  78,  28,  79,  48,  82, 106])

# Vector Operation

In [30]:
arr2=np.random.randint(1,100,10)
arr2

array([80, 32, 81, 51, 27,  3, 58, 89, 59, 35])

In [32]:
 arr2d1=np.random.randint(1,100,size=(4,5))
 arr2d2=np.random.randint(1,100,size=(4,5))

In [33]:
arr2d1

array([[32, 21, 22, 21, 35],
       [92,  8,  8, 94, 31],
       [99, 96, 28, 83,  8],
       [52,  4, 86, 99, 88]])

In [34]:
arr2d2

array([[81, 39, 30, 80, 77],
       [ 3, 55,  8, 14, 18],
       [42, 96, 76, 39, 71],
       [62,  8, 94, 11, 95]])

In [40]:

arr3d1=np.random.randint(1,100,size=(3,4,5))
arr3d1



array([[[58, 14, 68,  6, 47],
        [72, 94, 22,  5, 10],
        [64, 26, 35, 87, 14],
        [28,  3, 97, 70, 93]],

       [[49, 39, 57, 53, 20],
        [84, 64, 91, 22, 84],
        [88, 62, 12, 62, 56],
        [14, 51, 96, 61, 14]],

       [[36, 81, 90, 55, 85],
        [27,  9,  6, 97, 80],
        [17, 68, 37, 24, 22],
        [19, 68, 79,  4, 69]]])

In [41]:
arr3d2=np.random.randint(1,100,size=(3,4,5))
arr3d2

array([[[ 6, 92, 70, 24, 53],
        [21, 53, 63, 90, 89],
        [64, 92, 41, 87, 49],
        [40, 34, 87, 92, 91]],

       [[37, 10, 28, 73, 85],
        [61, 48, 88, 15, 14],
        [10,  1, 90, 28, 91],
        [45, 16, 31, 80, 34]],

       [[75, 68, 29, 98,  3],
        [50, 81, 93, 12,  9],
        [12, 33, 61, 30, 24],
        [14, 18, 68, 50, 65]]])

In [39]:
arr3d1-arr3d2

array([[[ 39, -25,  34, -41, -42],
        [-52,  12, -53,  45, -35],
        [ 48, -28,  -4,   6,  65],
        [-54,  14,  21,   1,  15]],

       [[-16,  94,  29,  49, -52],
        [ 31,   4,  -8, -67,  24],
        [-13,   9,  -9,   9,   1],
        [ 19,  18, -62, -12,  58]],

       [[ 19,  53,  44,  31,  32],
        [ 64, -37,  75, -38,  20],
        [ 56,  -1,  25,  29, -22],
        [  0,  -3, -11,   6,  56]]])

In [42]:
arr3d1.mean()

49.416666666666664

In [44]:
(arr3d1-arr3d1.mean())**2


array([[[7.36736111e+01, 1.25434028e+03, 3.45340278e+02, 1.88500694e+03,
         5.84027778e+00],
        [5.10006944e+02, 1.98767361e+03, 7.51673611e+02, 1.97284028e+03,
         1.55367361e+03],
        [2.12673611e+02, 5.48340278e+02, 2.07840278e+02, 1.41250694e+03,
         1.25434028e+03],
        [4.58673611e+02, 2.15450694e+03, 2.26417361e+03, 4.23673611e+02,
         1.89950694e+03]],

       [[1.73611111e-01, 1.08506944e+02, 5.75069444e+01, 1.28402778e+01,
         8.65340278e+02],
        [1.19600694e+03, 2.12673611e+02, 1.72917361e+03, 7.51673611e+02,
         1.19600694e+03],
        [1.48867361e+03, 1.58340278e+02, 1.40000694e+03, 1.58340278e+02,
         4.33402778e+01],
        [1.25434028e+03, 2.50694444e+00, 2.17000694e+03, 1.34173611e+02,
         1.25434028e+03]],

       [[1.80006944e+02, 9.97506944e+02, 1.64700694e+03, 3.11736111e+01,
         1.26617361e+03],
        [5.02506944e+02, 1.63350694e+03, 1.88500694e+03, 2.26417361e+03,
         9.35340278e+02],
      

In [52]:
l1=[10,20,30,40]
def standard_array(l1):
    arr=np.array(l1)
    return (np.sum((arr-arr.mean())**2)/(len(arr)-1))**0.5
l1 
standard_array(l1)

12.909944487358056