In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,100,10)
arr

array([ 8, 95,  3, 11, 88, 28, 53, 85, 63, 33])

In [7]:
arr.sort( )

In [8]:
arr


array([ 3,  8, 11, 28, 33, 53, 63, 85, 88, 95])

In [10]:
arr[::-1]

array([95, 88, 85, 63, 53, 33, 28, 11,  8,  3])

In [12]:
np.flip(arr)

array([95, 88, 85, 63, 53, 33, 28, 11,  8,  3])

In [13]:
arr

array([ 3,  8, 11, 28, 33, 53, 63, 85, 88, 95])

In [21]:
np.sort(arr)

array([ 3,  8, 11, 28, 33, 53, 63, 85, 88, 95])

In [22]:
cls

In [23]:
arr

array([ 3,  8, 11, 28, 33, 53, 63, 85, 88, 95])

In [24]:
arr


array([ 3,  8, 11, 28, 33, 53, 63, 85, 88, 95])

In [25]:
arr2=np.random.randint(1,100,10)
arr2

array([35, 94, 97, 59,  9, 97, 96, 66, 97, 26])

In [26]:
np.flip(arr2)

array([26, 97, 66, 96, 97,  9, 59, 97, 94, 35])

In [27]:
np.sort(arr2)

array([ 9, 26, 35, 59, 66, 94, 96, 97, 97, 97])

In [28]:
 arr

array([ 3,  8, 11, 28, 33, 53, 63, 85, 88, 95])

In [30]:
np.where(arr>50)[0]

array([5, 6, 7, 8, 9], dtype=int64)

## add 5 no, if no less than 35 
## (condition, if condition true, else) : syntax

In [31]:
np.where(arr>=35,arr,arr+5)

array([ 8, 13, 16, 33, 38, 53, 63, 85, 88, 95])

In [32]:
arr

array([ 3,  8, 11, 28, 33, 53, 63, 85, 88, 95])

### increment salary of emplyee by 5 % if saray 3500

In [34]:
salary=np.random.randint(25000,55000,10)

In [35]:
salary

array([39059, 51328, 31063, 33699, 40242, 42680, 37838, 50545, 34005,
       44758])

In [38]:
np.where(salary>35000,salary*0.05+salary,salary).astype('int')

array([41011, 53894, 31063, 33699, 42254, 44814, 39729, 53072, 34005,
       46995])

In [45]:
np.where(salary<35000,salary*1.03,np.where((salary>35000) & (salary<45000),salary*1.08,salary*1.13)).astype('int')

array([42183, 58000, 31994, 34709, 43461, 46094, 40865, 57115, 35025,
       48338])

### np.where 2D case

In [48]:
arr2d=np.random.randint(1,100,size=(4,5))

In [49]:
np.where(arr>50)

(array([5, 6, 7, 8, 9], dtype=int64),)

In [50]:
arr2d

array([[22, 97, 21, 30, 13],
       [46,  2, 87, 38, 95],
       [ 2, 31, 77, 32, 29],
       [64, 78, 68, 26, 73]])

In [51]:
np.where(arr2d>50)

(array([0, 1, 1, 2, 3, 3, 3, 3], dtype=int64),
 array([1, 2, 4, 2, 0, 1, 2, 4], dtype=int64))

## unique()

In [53]:
arr=np.array(['python','python','java','javascript','c','c++','python'])
arr

array(['python', 'python', 'java', 'javascript', 'c', 'c++', 'python'],
      dtype='<U10')

In [55]:
np.unique(arr,return_counts=True)

(array(['c', 'c++', 'java', 'javascript', 'python'], dtype='<U10'),
 array([1, 1, 1, 1, 3], dtype=int64))

## put delete insert

In [56]:
arr3=np.random.randint(1,100,10)

In [57]:
arr3

array([30, 34, 24, 91, 49, 22, 20,  1, 82, 99])

In [58]:
np.put(arr3,[1,4],[24,46])

In [59]:
arr3


array([30, 24, 24, 91, 46, 22, 20,  1, 82, 99])

In [60]:
np.insert(arr3,[1],111)

array([ 30, 111,  24,  24,  91,  46,  22,  20,   1,  82,  99])